dist: xenial
language: python
python:
 - "3.7"

cache: pip

install:
  - pip install -r requirements.txt

jobs:
  include:
    - name: "tests"
      script: "./quiz/manage.py test"
    - name: "linter"
      script: "pylint quizzes quiz"
    - name: "type analysis"
      script: "mypy quizzes quiz"