# Generated by Django 2.1.7 on 2019-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Title', 'Title'), ('Stats', 'Statistics')], default='Title', max_length=2),
        ),
    ]
