# Generated by Django 2.1.7 on 2019-05-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='article_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
