# Generated by Django 2.1.7 on 2019-05-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
    ]
