# Generated by Django 2.1.7 on 2019-05-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_question_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question_number',
            new_name='questions_amount',
        ),
    ]
