# Generated by Django 2.1.7 on 2019-05-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20190530_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions_amount',
        ),
    ]
